[package]
name = "lcp"
version = "0.4.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "4"
unicode-segmentation = "1"
arboard = "3.2"

[dev-dependencies]
stringreader = "0.1"
